# SLURM cgroup configuration

CgroupAutomount=yes
CgroupReleaseAgentDir="/etc/slurm/cgroup"

ConstrainCores=yes
ConstrainRAMSpace=yes
ConstrainSwapSpace=yes
ConstrainDevices=yes

# Memory limits
AllowedRAMSpace=100
AllowedSwapSpace=0

# Device access
AllowedDevicesFile="/etc/slurm/cgroup_allowed_devices_file.conf"
