[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:munged]
command=/usr/sbin/munged -F
user=munge
autostart=true
autorestart=true
stdout_logfile=/var/log/munge/munged.log
stderr_logfile=/var/log/munge/munged_err.log
priority=10

[program:dockerd]
command=/usr/bin/dockerd
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/docker/dockerd.log
stderr_logfile=/var/log/docker/dockerd_err.log
priority=15

[program:slurmd]
command=/usr/sbin/slurmd -D -vvv
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/slurm/slurmd.log
stderr_logfile=/var/log/slurm/slurmd_err.log
priority=20
depends_on=munged,dockerd
