[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:munged]
command=/usr/sbin/munged -F
user=munge
autostart=true
autorestart=true
stdout_logfile=/var/log/munge/munged.log
stderr_logfile=/var/log/munge/munged_err.log
priority=10

[program:slurmctld]
command=/usr/sbin/slurmctld -D -vvv
user=slurm
autostart=true
autorestart=true
stdout_logfile=/var/log/slurm/slurmctld.log
stderr_logfile=/var/log/slurm/slurmctld_err.log
priority=20
depends_on=munged

[program:slurmdbd]
command=/usr/sbin/slurmdbd -D -vvv
user=slurm
autostart=true
autorestart=true
stdout_logfile=/var/log/slurm/slurmdbd.log
stderr_logfile=/var/log/slurm/slurmdbd_err.log
priority=15
depends_on=munged
