// Historically this component exposed a full summary-model configuration form:
// provider picker (OpenAI / Claude / Groq / OpenRouter / RelayAI), custom
// endpoint URL, model name, API key, max_tokens / temperature / top_p sliders,
// and a "Test Connection" button. Every field revealed internals — the gateway
// base URL (www.example.com/api/v1/ai) and the underlying model tag
// (gemma4:e2b) — and the provider selection forked the request pipeline.
//
// Today all summary requests go through the Relay gateway, so there is nothing
// for the user to configure. We keep the module for backwards-compat of the
// `ModelConfig` type (still imported by SummaryModelSettings / SettingsModal /
// ConfigContext), but the rendered surface is a static info card — no inputs,
// no URLs, no model names.

import { Alert, AlertDescription } from '@/components/ui/alert'

export interface ModelConfig {
  provider: 'relay-ai'
  model: string
  whisperModel: string
  apiKey?: string | null
  relayAIEndpoint?: string | null
  relayAIModel?: string | null
  relayAIApiKey?: string | null
  maxTokens?: number | null
  temperature?: number | null
  topP?: number | null
}

interface ModelSettingsModalProps {
  modelConfig: ModelConfig
  setModelConfig: (config: ModelConfig | ((prev: ModelConfig) => ModelConfig)) => void
  onSave: (config: ModelConfig) => void
  skipInitialFetch?: boolean
}

// Props are retained so callers compile unchanged. We ignore them here — the
// gateway config is resolved on the Rust side at request time and the user has
// no knobs to turn on the summary side.
export function ModelSettingsModal(_props: ModelSettingsModalProps) {
  return (
    <div className="space-y-4">
      <Alert>
        <AlertDescription>
          Meeting summaries are generated by Relay AI. No additional setup is required.
        </AlertDescription>
      </Alert>
    </div>
  )
}
